[package]
name = "canny2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
ndarray = "0.15.6"
ndarray-image = "0.3.0"
rayon = "1.8.0"
fast-math = "0.1.1"
